fieldLayouts:
  7b26eba0-c818-45e3-85a0-d80a60c7d164:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a6b37a3b-7ccd-4cbb-ad27-24c18f19fc0c # NavLinks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bd94565-9374-405d-b297-fd85b0b05165
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ad0e006-a978-40f9-8625-0ed1ec065a7a
        userCondition: null
handle: ledenNavigatie
name: 'Leden Navigatie'
sortOrder: 2
