columnSuffix: null
handle: beginUur
instructions: null
name: 'Begin Uur'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
