columnSuffix: null
handle: eindUur
instructions: null
name: 'Eind Uur'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
