columnSuffix: null
handle: eventLocation
instructions: null
name: 'Event Location'
searchable: false
settings:
  maxAddresses: 1
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
