columnSuffix: null
handle: eventDescription
instructions: null
name: 'Event Description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: ba6a27d7-3991-4ef1-bc38-3305244869d7 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
