columnSuffix: null
handle: tags
instructions: null
name: Tags
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Voeg jou tag toe'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:c751aa6a-595b-43e9-b450-fd22d6660bf6' # Tags
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
