altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  924eb7e4-4cd7-430a-944f-885a97065253:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4d74241e-42fd-4e87-9211-72377655b3d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a955d695-0cfc-46f0-8d0e-e08918a1f04c
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
