defaultPlacement: end
enableVersioning: true
entryTypes:
  - f281ce47-179e-4fed-ae32-f348a72e2505 # Gallerij
handle: gallerij
maxAuthors: 1
name: Gallerij
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  82d7d074-f812-4c3c-a7c2-e94695f6b1f4: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: _gallerij/_entry.twig
    uriFormat: 'gallerij/{slug}'
type: channel
