defaultPlacement: end
enableVersioning: true
entryTypes:
  - 47bec586-931e-4fb9-ae84-2b33e28cee23 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  82d7d074-f812-4c3c-a7c2-e94695f6b1f4: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
