defaultPlacement: end
enableVersioning: true
entryTypes:
  - a629c1c2-fdd7-4d89-b5c0-d80c8b3d204a # Login
handle: login
maxAuthors: 1
name: login
propagationMethod: all
siteSettings:
  82d7d074-f812-4c3c-a7c2-e94695f6b1f4: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: _login.twig
    uriFormat: login
type: single
