defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2597aab7-1377-44de-bca2-ba1e6b9b2113 # Page
handle: login
maxAuthors: 1
name: login
propagationMethod: all
siteSettings:
  82d7d074-f812-4c3c-a7c2-e94695f6b1f4: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: _login.twig
    uriFormat: login
type: single
