color: null
fieldLayouts:
  0a07b7d5-2af9-4c25-b0be-0061064469c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c1c40bc-08ce-4e94-bb88-dc6daa1e79a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10008e6f-6ccb-4b28-9969-670eafdd8963 # HeroTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dd8034a-1be5-43de-ad4e-f448b99e479c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dde969b7-31d9-4d7c-b2b0-c5ddd0aa5bb5 # Formulier
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 680af9db-08b9-483d-b83d-61631e7f5cc8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f57928a8-5b7b-45f4-a5e9-2e4ec0aa0dc8
        userCondition: null
handle: contact
hasTitleField: false
icon: at
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
