color: null
fieldLayouts:
  58d115cb-81ab-453c-9976-bdbaf43b29da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f997649d-5b90-44f9-b988-f0a2a9f83c6a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23802245-e6ba-488e-845f-25e60f1b018d
        userCondition: null
handle: duikInformatie
hasTitleField: true
icon: ''
name: 'Duik Informatie'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
