color: null
fieldLayouts:
  58d115cb-81ab-453c-9976-bdbaf43b29da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f997649d-5b90-44f9-b988-f0a2a9f83c6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d72d7795-44ab-404d-9827-b8f195919d3b # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8d6eb8b-91ea-4edb-90ad-77ff27e531d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 21b37d30-09cf-4c46-8f63-88e670aa6c91 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7899a3d-aca9-4617-af31-0b90ace803c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23802245-e6ba-488e-845f-25e60f1b018d
        userCondition: null
handle: duikInformatie
hasTitleField: true
icon: question
name: 'Duik Informatie'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
