color: null
fieldLayouts:
  7f9e42ae-9f72-4048-9306-eb89be450e51:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Plaats
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ca894d5d-a6d1-4351-8702-540277832fb8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 10008e6f-6ccb-4b28-9969-670eafdd8963 # HeroTitle
            handle: duikTitle
            includeInCards: false
            instructions: null
            label: 'Duik Title'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b5cad12-ae8e-4745-8ff2-ec44e754ee7b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: aca6b6f8-f4d0-4249-a4d5-755090a73921
            userCondition: null
          -
            elementCondition: null
            fieldUid: f47a425f-ef1d-40ce-9674-1a0c7e59a56b # Datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cf948c6-05f2-46a9-a54b-f1a55afec27f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: db3a5384-72e7-41bd-9a3e-73c0c097b964 # Begin Uur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33825e51-7c7c-4163-84bc-ef00324e7537
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb125a24-cfc8-4055-b270-9a13e3c0cfe4 # Eind Uur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23cd1297-e522-4449-95d2-2ba98080dfbe
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: a1f8342f-22c4-431a-94c2-7c019b702b6c
        userCondition: null
handle: duiken
hasTitleField: true
icon: person-swimming
name: Duiken
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
