color: null
fieldLayouts:
  b861e5a2-5fff-48c7-aceb-e3777c1774d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecf58c52-09b6-426f-a302-448b15eb140e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff299e46-0e67-4a7a-8937-efec8d7b148c # Event Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b50e16b-cc4b-4e72-9773-97eae98adc21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d6e437c-cad8-40c4-8f06-4fc70d34c7b7 # Event Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2d851d1-88bf-47f9-adab-f8909d544bf3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d72d7795-44ab-404d-9827-b8f195919d3b # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1162be63-ceb5-41c3-862d-6f363e8c33f6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: 41b4df07-0e2a-4f8f-b5a6-245bdda6591d
            userCondition: null
          -
            elementCondition: null
            fieldUid: 97f6ef56-6d55-41c8-a43f-04ec062224ff # Event Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c847a31-4e9c-4af3-ba9a-a6a85eaa6a8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0a6fc2fa-5bb8-490a-95d5-715f9a06ccb4
            userCondition: null
          -
            elementCondition: null
            fieldUid: f47a425f-ef1d-40ce-9674-1a0c7e59a56b # Datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 745c38c5-f280-4a01-9c3b-c947b7673cd1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: db3a5384-72e7-41bd-9a3e-73c0c097b964 # Begin Uur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79fce7ef-e800-40ca-8679-894a0c77ddc2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb125a24-cfc8-4055-b270-9a13e3c0cfe4 # Eind Uur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55156704-dc24-40e6-ac4f-60abc8f8212a
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 3b3516b6-6abd-464e-bb18-b311e1f12196
        userCondition: null
handle: evenementen
hasTitleField: true
icon: party-horn
name: evenementen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
