color: null
fieldLayouts:
  a7dd54fc-ef58-4af8-8a8f-8b96435f86d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4b52a3dd-4728-4494-a414-48c6cb5c5f82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10008e6f-6ccb-4b28-9969-670eafdd8963 # HeroTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f1fff2e-390f-45a5-97a8-d1dc739a890d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 10008e6f-6ccb-4b28-9969-670eafdd8963 # HeroTitle
            handle: HeroTagLine
            includeInCards: false
            instructions: null
            label: HeroTagline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03d9cec9-3652-4fbf-81bd-bbc50bf58a02
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b63f96f3-641c-45b7-b75d-ee3f8a5fce01
            userCondition: null
          -
            elementCondition: null
            fieldUid: d72d7795-44ab-404d-9827-b8f195919d3b # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41e269fd-fa0f-4794-a59e-4f80bc7e9bb6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a929e144-72f1-40c6-bd10-bc396a2d7696 # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f1058fa-28dc-420e-9db5-7acf19c9a665
            userCondition: null
            warning: null
            width: 50
        name: Hero
        uid: 72bf1b4e-e248-4fa8-8990-d9821d93d78c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a1f5ff61-2261-4570-be4f-b52acd6857cb # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3845c18-a16e-4df6-b667-cec38bff2d29
            userCondition: null
            warning: null
            width: 100
        name: Sponsors
        uid: f95e22ef-b8c5-442e-ba3d-b7084483a55b
        userCondition: null
handle: home
hasTitleField: false
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Home
titleTranslationKeyFormat: null
titleTranslationMethod: site
