color: null
fieldLayouts:
  804bf296-feba-47ba-849c-5db5cd01f07f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1bab98ad-712d-4a60-a5be-7caccf525088
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98cf5e85-dfb5-4bdb-a863-fea510a9f1f3 # Link Destination
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10d46c25-52d5-4f07-9d05-11d6228d6e5f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9f28f59d-a75e-4685-a308-6d6d34a46369
        userCondition: null
handle: links
hasTitleField: true
icon: link
name: links
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
