tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\UsernameField
        uid: 7dff24c5-5829-448b-9873-83a4bf377cde
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: 2c3e0e93-6001-4e70-88e2-7aec66f4c59f
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 10008e6f-6ccb-4b28-9969-670eafdd8963 # HeroTitle
        handle: wachtwoord
        includeInCards: false
        instructions: null
        label: wachtwoord
        providesThumbs: false
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 964d7e1f-0f1b-4278-b587-3aa889076a59
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: ec00bda8-6447-4993-a706-b6826a2c7f7e
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: 3c8e153a-974b-4f72-beda-2e6680992572
        userCondition: null
        width: 100
    name: Content
    uid: 148723b2-9c4d-46c2-8401-0e70f0bda812
    userCondition: null
