allowPublicRegistration: true
deactivateByDefault: false
defaultGroup: ''
photoSubpath: /users
photoVolumeUid: c1d29cef-84a3-4a6c-aa79-b927fc624241 # Images
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: false
